# ==============================================================================
# joystick 手柄读取参数
# ==============================================================================
control:
  fps: 30  # 数据输出帧率
